export const ActionTypes = {
  AUTH: 'AUTH',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_REQUESTS: 'GET_REQUESTS',
  CREATE_REQUEST: 'CREATE_REQUEST',
  SET_TAB: 'SET_TAB',
  ADD_TO_LOVES: 'ADD_TO_LOVES',
  GET_LOVES: 'GET_LOVES',
};
